download_tests:
	python3 download-tests.py
	chmod -R 755 tests

csvversat:
	python3 quantile-generator.py results/versat.*.results.standard.uuf100-430.xml.bz2 > versatuuf100.csv
	python3 quantile-generator.py results/versat.*.results.standard.uf100-430.xml.bz2 > versatuf100.csv
	python3 quantile-generator.py results/versat.*.results.standard.uuf150-645.xml.bz2 > versatuuf150.csv
	python3 quantile-generator.py results/versat.*.results.standard.uf150-645.xml.bz2 > versatuf150.csv
	python3 quantile-generator.py results/versat.*.results.standard.uuf175-753.xml.bz2 > versatuuf175.csv
	python3 quantile-generator.py results/versat.*.results.standard.uf175-753.xml.bz2 > versatuf175.csv
	python3 quantile-generator.py results/versat.*.results.standard.uuf200-860.xml.bz2 > versatuuf200.csv
	python3 quantile-generator.py results/versat.*.results.standard.uf200-860.xml.bz2 > versatuf200.csv
	python3 quantile-generator.py results/versat.*.results.standard.uuf100-430.xml.bz2 results/versat.*.results.standard.uf100-430.xml.bz2 > versat100.csv
	python3 quantile-generator.py results/versat.*.results.standard.uuf150-645.xml.bz2 results/versat.*.results.standard.uf150-645.xml.bz2 > versat150.csv
	python3 quantile-generator.py results/versat.*.results.standard.uuf175-753.xml.bz2 results/versat.*.results.standard.uf175-753.xml.bz2 > versat175.csv
	python3 quantile-generator.py results/versat.*.results.standard.uuf200-860.xml.bz2 results/versat.*.results.standard.uf200-860.xml.bz2 > versat200.csv
	python3 quantile-generator.py results/versat.*.results.standard.xml.bz2 > versatall.csv

csv:
	python3 quantile-generator.py results/truesat.*.results.standard.uuf100-430.xml.bz2 > truesatuuf100.csv
	python3 quantile-generator.py results/truesat.*.results.standard.uf100-430.xml.bz2 > truesatuf100.csv
	python3 quantile-generator.py results/truesat.*.results.standard.uuf150-645.xml.bz2 > truesatuuf150.csv
	python3 quantile-generator.py results/truesat.*.results.standard.uf150-645.xml.bz2 > truesatuf150.csv
	python3 quantile-generator.py results/truesat.*.results.standard.uuf175-753.xml.bz2 > truesatuuf175.csv
	python3 quantile-generator.py results/truesat.*.results.standard.uf175-753.xml.bz2 > truesatuf175.csv
	python3 quantile-generator.py results/truesat.*.results.standard.uuf200-860.xml.bz2 > truesatuuf200.csv
	python3 quantile-generator.py results/truesat.*.results.standard.uf200-860.xml.bz2 > truesatuf200.csv
	python3 quantile-generator.py results/truesat.*.results.standard.uuf100-430.xml.bz2 results/truesat.*.results.standard.uf100-430.xml.bz2 > truesat100.csv
	python3 quantile-generator.py results/truesat.*.results.standard.uuf150-645.xml.bz2 results/truesat.*.results.standard.uf150-645.xml.bz2 > truesat150.csv
	python3 quantile-generator.py results/truesat.*.results.standard.uuf175-753.xml.bz2 results/truesat.*.results.standard.uf175-753.xml.bz2 > truesat175.csv
	python3 quantile-generator.py results/truesat.*.results.standard.uuf200-860.xml.bz2 results/truesat.*.results.standard.uf200-860.xml.bz2 > truesat200.csv
	python3 quantile-generator.py results/truesat.*.results.standard.xml.bz2 > truesatall.csv
	python3 quantile-generator.py results/truesatbig.*.results.standard.uuf100-430.xml.bz2 > truesatbiguuf100.csv
	python3 quantile-generator.py results/truesatbig.*.results.standard.uf100-430.xml.bz2 > truesatbiguf100.csv
	python3 quantile-generator.py results/truesatbig.*.results.standard.uuf150-645.xml.bz2 > truesatbiguuf150.csv
	python3 quantile-generator.py results/truesatbig.*.results.standard.uf150-645.xml.bz2 > truesatbiguf150.csv
	python3 quantile-generator.py results/truesatbig.*.results.standard.uuf175-753.xml.bz2 > truesatbiguuf175.csv
	python3 quantile-generator.py results/truesatbig.*.results.standard.uf175-753.xml.bz2 > truesatbiguf175.csv
	python3 quantile-generator.py results/truesatbig.*.results.standard.uuf200-860.xml.bz2 > truesatbiguuf200.csv
	python3 quantile-generator.py results/truesatbig.*.results.standard.uf200-860.xml.bz2 > truesatbiguf200.csv
	python3 quantile-generator.py results/truesatbig.*.results.standard.uuf100-430.xml.bz2 results/truesatbig.*.results.standard.uf100-430.xml.bz2 > truesatbig100.csv
	python3 quantile-generator.py results/truesatbig.*.results.standard.uuf150-645.xml.bz2 results/truesatbig.*.results.standard.uf150-645.xml.bz2 > truesatbig150.csv
	python3 quantile-generator.py results/truesatbig.*.results.standard.uuf175-753.xml.bz2 results/truesatbig.*.results.standard.uf175-753.xml.bz2 > truesatbig175.csv
	python3 quantile-generator.py results/truesatbig.*.results.standard.uuf200-860.xml.bz2 results/truesatbig.*.results.standard.uf200-860.xml.bz2 > truesatbig200.csv
	python3 quantile-generator.py results/truesatbig.*.results.standard.xml.bz2 > truesatbigall.csv
	python3 quantile-generator.py results/swansea.*.results.standard.uuf100-430.xml.bz2 > swanseauuf100.csv
	python3 quantile-generator.py results/swansea.*.results.standard.uf100-430.xml.bz2 > swanseauf100.csv
	python3 quantile-generator.py results/swansea.*.results.standard.uuf150-645.xml.bz2 > swanseauuf150.csv
	python3 quantile-generator.py results/swansea.*.results.standard.uf150-645.xml.bz2 > swanseauf150.csv
	python3 quantile-generator.py results/swansea.*.results.standard.uuf175-753.xml.bz2 > swanseauuf175.csv
	python3 quantile-generator.py results/swansea.*.results.standard.uf175-753.xml.bz2 > swanseauf175.csv
	python3 quantile-generator.py results/swansea.*.results.standard.uuf200-860.xml.bz2 > swanseauuf200.csv
	python3 quantile-generator.py results/swansea.*.results.standard.uf200-860.xml.bz2 > swanseauf200.csv
	python3 quantile-generator.py results/swansea.*.results.standard.uuf100-430.xml.bz2 results/swansea.*.results.standard.uf100-430.xml.bz2 > swansea100.csv
	python3 quantile-generator.py results/swansea.*.results.standard.uuf150-645.xml.bz2 results/swansea.*.results.standard.uf150-645.xml.bz2 > swansea150.csv
	python3 quantile-generator.py results/swansea.*.results.standard.uuf175-753.xml.bz2 results/swansea.*.results.standard.uf175-753.xml.bz2 > swansea175.csv
	python3 quantile-generator.py results/swansea.*.results.standard.uuf200-860.xml.bz2 results/swansea.*.results.standard.uf200-860.xml.bz2 > swansea200.csv
	python3 quantile-generator.py results/swansea.*.results.standard.xml.bz2 > swanseaall.csv
	python3 quantile-generator.py results/minisat.*.results.standard.uuf100-430.xml.bz2 > minisatuuf100.csv
	python3 quantile-generator.py results/minisat.*.results.standard.uf100-430.xml.bz2 > minisatuf100.csv
	python3 quantile-generator.py results/minisat.*.results.standard.uuf150-645.xml.bz2 > minisatuuf150.csv
	python3 quantile-generator.py results/minisat.*.results.standard.uf150-645.xml.bz2 > minisatuf150.csv
	python3 quantile-generator.py results/minisat.*.results.standard.uuf175-753.xml.bz2 > minisatuuf175.csv
	python3 quantile-generator.py results/minisat.*.results.standard.uf175-753.xml.bz2 > minisatuf175.csv
	python3 quantile-generator.py results/minisat.*.results.standard.uuf200-860.xml.bz2 > minisatuuf200.csv
	python3 quantile-generator.py results/minisat.*.results.standard.uf200-860.xml.bz2 > minisatuf200.csv
	python3 quantile-generator.py results/minisat.*.results.standard.uuf100-430.xml.bz2 results/minisat.*.results.standard.uf100-430.xml.bz2 > minisat100.csv
	python3 quantile-generator.py results/minisat.*.results.standard.uuf150-645.xml.bz2 results/minisat.*.results.standard.uf150-645.xml.bz2 > minisat150.csv
	python3 quantile-generator.py results/minisat.*.results.standard.uuf175-753.xml.bz2 results/minisat.*.results.standard.uf175-753.xml.bz2 > minisat175.csv
	python3 quantile-generator.py results/minisat.*.results.standard.uuf200-860.xml.bz2 results/minisat.*.results.standard.uf200-860.xml.bz2 > minisat200.csv
	python3 quantile-generator.py results/minisat.*.results.standard.xml.bz2 > minisatall.csv
	python3 quantile-generator.py results/isasat_ml.*.results.standard.uuf100-430.xml.bz2 > isasat_mluuf100.csv
	python3 quantile-generator.py results/isasat_ml.*.results.standard.uf100-430.xml.bz2 > isasat_mluf100.csv
	python3 quantile-generator.py results/isasat_ml.*.results.standard.uuf150-645.xml.bz2 > isasat_mluuf150.csv
	python3 quantile-generator.py results/isasat_ml.*.results.standard.uf150-645.xml.bz2 > isasat_mluf150.csv
	python3 quantile-generator.py results/isasat_ml.*.results.standard.uuf175-753.xml.bz2 > isasat_mluuf175.csv
	python3 quantile-generator.py results/isasat_ml.*.results.standard.uf175-753.xml.bz2 > isasat_mluf175.csv
	python3 quantile-generator.py results/isasat_ml.*.results.standard.uuf200-860.xml.bz2 > isasat_mluuf200.csv
	python3 quantile-generator.py results/isasat_ml.*.results.standard.uf200-860.xml.bz2 > isasat_mluf200.csv
	python3 quantile-generator.py results/isasat_ml.*.results.standard.uuf100-430.xml.bz2 results/isasat_ml.*.results.standard.uf100-430.xml.bz2 > isasat_ml100.csv
	python3 quantile-generator.py results/isasat_ml.*.results.standard.uuf150-645.xml.bz2 results/isasat_ml.*.results.standard.uf150-645.xml.bz2 > isasat_ml150.csv
	python3 quantile-generator.py results/isasat_ml.*.results.standard.uuf175-753.xml.bz2 results/isasat_ml.*.results.standard.uf175-753.xml.bz2 > isasat_ml175.csv
	python3 quantile-generator.py results/isasat_ml.*.results.standard.uuf200-860.xml.bz2 results/isasat_ml.*.results.standard.uf200-860.xml.bz2 > isasat_ml200.csv
	python3 quantile-generator.py results/isasat_ml.*.results.standard.xml.bz2 > isasat_mlall.csv
	python3 quantile-generator.py results/cpp.*.results.standard.uuf100-430.xml.bz2 > cppuuf100.csv
	python3 quantile-generator.py results/cpp.*.results.standard.uf100-430.xml.bz2 > cppuf100.csv
	python3 quantile-generator.py results/cpp.*.results.standard.uuf150-645.xml.bz2 > cppuuf150.csv
	python3 quantile-generator.py results/cpp.*.results.standard.uf150-645.xml.bz2 > cppuf150.csv
	python3 quantile-generator.py results/cpp.*.results.standard.uuf175-753.xml.bz2 > cppuuf175.csv
	python3 quantile-generator.py results/cpp.*.results.standard.uf175-753.xml.bz2 > cppuf175.csv
	python3 quantile-generator.py results/cpp.*.results.standard.uuf200-860.xml.bz2 > cppuuf200.csv
	python3 quantile-generator.py results/cpp.*.results.standard.uf200-860.xml.bz2 > cppuf200.csv
	python3 quantile-generator.py results/cpp.*.results.standard.uuf100-430.xml.bz2 results/cpp.*.results.standard.uf100-430.xml.bz2 > cpp100.csv
	python3 quantile-generator.py results/cpp.*.results.standard.uuf150-645.xml.bz2 results/cpp.*.results.standard.uf150-645.xml.bz2 > cpp150.csv
	python3 quantile-generator.py results/cpp.*.results.standard.uuf175-753.xml.bz2 results/cpp.*.results.standard.uf175-753.xml.bz2 > cpp175.csv
	python3 quantile-generator.py results/cpp.*.results.standard.uuf200-860.xml.bz2 results/cpp.*.results.standard.uf200-860.xml.bz2 > cpp200.csv
	python3 quantile-generator.py results/cpp.*.results.standard.xml.bz2 > cppall.csv
	python3 quantile-generator.py results/cs.*.results.standard.uuf100-430.xml.bz2 > csuuf100.csv
	python3 quantile-generator.py results/cs.*.results.standard.uf100-430.xml.bz2 > csuf100.csv
	python3 quantile-generator.py results/cs.*.results.standard.uuf150-645.xml.bz2 > csuuf150.csv
	python3 quantile-generator.py results/cs.*.results.standard.uf150-645.xml.bz2 > csuf150.csv
	python3 quantile-generator.py results/cs.*.results.standard.uuf175-753.xml.bz2 > csuuf175.csv
	python3 quantile-generator.py results/cs.*.results.standard.uf175-753.xml.bz2 > csuf175.csv
	python3 quantile-generator.py results/cs.*.results.standard.uuf200-860.xml.bz2 > csuuf200.csv
	python3 quantile-generator.py results/cs.*.results.standard.uf200-860.xml.bz2 > csuf200.csv
	python3 quantile-generator.py results/cs.*.results.standard.uuf100-430.xml.bz2 results/cs.*.results.standard.uf100-430.xml.bz2 > cs100.csv
	python3 quantile-generator.py results/cs.*.results.standard.uuf150-645.xml.bz2 results/cs.*.results.standard.uf150-645.xml.bz2 > cs150.csv
	python3 quantile-generator.py results/cs.*.results.standard.uuf175-753.xml.bz2 results/cs.*.results.standard.uf175-753.xml.bz2 > cs175.csv
	python3 quantile-generator.py results/cs.*.results.standard.uuf200-860.xml.bz2 results/cs.*.results.standard.uf200-860.xml.bz2 > cs200.csv
	python3 quantile-generator.py results/cs.*.results.standard.xml.bz2 > csall.csv

plots_tstsb:
	gnuplot ts-vs-tsb-100.gp
	gnuplot ts-vs-tsb-150.gp
	gnuplot ts-vs-tsb-175.gp
	gnuplot ts-vs-tsb-200.gp
	gnuplot ts-vs-tsb-all.gp

plots_dpll:
	gnuplot dpll-100.gp
	gnuplot dpll-150.gp
	gnuplot dpll-175.gp
	gnuplot dpll-200.gp
	gnuplot dpll-all.gp

plots_cdcl:
	gnuplot cdcl-100.gp
	gnuplot cdcl-150.gp
	gnuplot cdcl-175.gp
	gnuplot cdcl-200.gp
	gnuplot cdcl-all.gp

plots: plots_tstsb plots_dpll plots_cdcl

all: bench_cpp bench_cs bench_truesat bench_truesat_bigints bench_swansea bench_isasat_ml bench_minisat

bench_cpp:
	benchexec cpp.xml --tool-directory /home/stefan/work/truesat/cpp_solver --read-only-dir / --overlay-dir /home

bench_cs:
	benchexec cs.xml --tool-directory /home/stefan/work/truesat/csharp_solver --read-only-dir / --overlay-dir /home

bench_truesat:
	benchexec truesat.xml --tool-directory /home/stefan/work/truesat/truesat_src --read-only-dir / --overlay-dir /home

bench_truesatnoopt:
	benchexec truesatnoopt.xml --tool-directory /home/stefan/work/truesat/truesat_src --read-only-dir / --overlay-dir /home

bench_truesat_bigints:
	benchexec truesatbig.xml --tool-directory /home/stefan/work/truesat/truesatbig_src --read-only-dir / --overlay-dir /home

bench_swansea:
	benchexec swansea.xml --tool-directory /home/stefan/software/HaskDPLL --read-only-dir / --overlay-dir /home

bench_isasat_ml:
	benchexec isasat_ml.xml --tool-directory /home/stefan/software/isafol/Weidenbach_Book/IsaSAT/code/ML --read-only-dir / --overlay-dir /home

bench_minisat:
	benchexec minisat.xml --tool-directory /home/stefan/software/minisat/core --read-only-dir / --overlay-dir /home

bench_versat:
	benchexec versat.xml --tool-directory /home/stefan/software/versat/ --read-only-dir / --overlay-dir /home
